      MODULE PRECISION
      INTEGER,  PARAMETER :: DIGITS = 15
      INTEGER,  PARAMETER :: POWER  = 307
      INTEGER,  PARAMETER :: dp = SELECTED_REAL_KIND(DIGITS,POWER)
      REAL(dp), PARAMETER :: EPS_ROUND_OFF  = 1.E-07  
      REAL(dp), PARAMETER :: REAL_MIN_VALUE = 1.E-37
      END MODULE PRECISION
